Update sensor.py
Error: Entity ide platform implements device_state_attributes

There are upcoming changes in HA 2022.2 that will deprecate the use of device_state_attributes, which needs to be renamed to extra_state_attributes.